#!/usr/bin/env python3

#import numpy as np
import json
from ctypes import *
from argparse import ArgumentParser
#import numpy as np
import struct
import os
import wave


try:

    lib = './setsecs2.so'
    dll = CDLL(lib)
    dll.sha256hash.restype = c_char_p #Override default return type
    #dll.getKeys.restype = POINTER(Userkeys) #Expect the output to be structure    

    f = open('record', 'r')
    ps = f.readlines()

#Pins need parsing
    ps[0] = ps[0].replace('[', '')
    ps[0] = ps[0].replace(']', '')
    ps[0] = ps[0].replace('"', '')
    pins = ps[0].split(', ')

#Now the pins have been imported and parsed in the pins variable
    #print(pins[0:len(pins)])

#Needs for loop
#The key generation is successful. The use of the keys is still undetermined (Whether they stay in c or come out here to python.
    userks = dll.getKeys(create_string_buffer(pins[0].encode('utf-8')))

    #print(userks)

except:
    raise Exception(
        "An issue is present with key generation!")


f.close()
